# Generated by Django 4.0.3 on 2022-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BGGId', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('AvgRating', models.FloatField()),
                ('Ratings', models.IntegerField()),
                ('ComMinPlaytime', models.IntegerField()),
                ('Thematic', models.BooleanField()),
                ('Strategy', models.BooleanField()),
                ('War', models.BooleanField()),
                ('Family', models.BooleanField()),
                ('CGS', models.BooleanField()),
                ('Abstract', models.BooleanField()),
                ('Party', models.BooleanField()),
                ('Child', models.BooleanField()),
            ],
        ),
    ]
